package com.mama.server.main.dao;

import java.util.List;

import com.mama.server.util.dao.mybatis.MyBatisDao;

@MyBatisDao
public interface OrderPayDAO {

	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_pay
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    int deleteByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_pay
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    int insert(OrderPayDO record);

    /** 根据payId查询对应的支付记录信息 */
    OrderPayDO selectOrderPayByPayId(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_pay
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    int updateByPrimaryKey(OrderPayDO record);    

	OrderPayDO selectByOrderId(String orderId);

	/** 根据房源定好号查询支付记录 */
	List<OrderPayDO> queryPayOrderListByOrderId(String orderId);
	
	/** 根据订单号查询最新一条支付成功的支付记录 */
	OrderPayDO queryLatestOrderPayByOrderId(String orderId);
}