package com.mama.server.main.dao;

import java.util.Date;

public class OrderPayDO {

	 /** 支付订单号 */
    private String payId;

    /** 商品订单id */
    private String orderId;

    /**  支付金额 */
    private String fee;

    /** 订单状态 */
    private String status;

    /** 账期日 */
    private String accountDate;

    /** 创建时间 */
    private Date createTime;

    /** 更新时间 */
    private Date updateTime;
    
    /** 支付类型 */
    private String payType;

    /** 订单支付来源：ios：ios客户端；android：android客户端；h5：h5客户端； */
    private String source;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.pay_id
     *
     * @return the value of t_order_pay.pay_id
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.pay_id
     *
     * @param payId the value for t_order_pay.pay_id
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.order_id
     *
     * @return the value of t_order_pay.order_id
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.order_id
     *
     * @param orderId the value for t_order_pay.order_id
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.fee
     *
     * @return the value of t_order_pay.fee
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.fee
     *
     * @param fee the value for t_order_pay.fee
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.status
     *
     * @return the value of t_order_pay.status
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.status
     *
     * @param status the value for t_order_pay.status
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.account_date
     *
     * @return the value of t_order_pay.account_date
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public String getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.account_date
     *
     * @param accountDate the value for t_order_pay.account_date
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setAccountDate(String accountDate) {
        this.accountDate = accountDate == null ? null : accountDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.create_time
     *
     * @return the value of t_order_pay.create_time
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.create_time
     *
     * @param createTime the value for t_order_pay.create_time
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_pay.update_time
     *
     * @return the value of t_order_pay.update_time
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_pay.update_time
     *
     * @param updateTime the value for t_order_pay.update_time
     *
     * @mbggenerated Tue May 31 20:42:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getPayType() {
		return payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
}